[database]
url = "mongodb://localhost:27017"
db_name="oss"
[redis]
url="redis://127.0.0.1:6379/"
[server]
host = "127.0.0.1"
port = 8080
[cache]
node_id=0
node_total=1
cache=true
[sys]
log_leve = "trace"  #trace debug info error warn
upload_path = "./upload"
md5_key="0000000000000000000000000000000"

