[database]
url = "mongodb://localhost:27017"
db_name = "oss"
[redis]
url = "redis://127.0.0.1:6379/"
[server]
host = "127.0.0.1"
port = 8080
[shard]
shard_address = "127.0.0.1:52000"
server_host = "127.0.0.1:50000"
[cache]
node_id = 0
node_total = 1
cache = true
[sys]
log_leve = "trace"  #trace debug info error warn
upload_path = "./upload"
md5_key = "0000000000000000000000000000000"
[kafka]
brokers = "localhost:9092"
topic_single = "im-p2p-msg"
topic_group = "im-group-msg"
[socket]
node_addr=
