# rustfmt.toml 配置
use_small_heuristics = "Max"      # 最小化换行（尽可能紧凑）
empty_item_single_line = true     # 空函数体保持单行
where_single_line = true          # where子句保持单行
max_width = 150
struct_field_align_threshold = 0
struct_lit_single_line = false
struct_lit_width = 0