[shard]
server_host = "127.0.0.1:50000"
[database]
url = "mongodb://localhost:27017"
db_name = "group"
[redis]
url = "redis://127.0.0.1:6379/"
[sys]
log_leve = "trace"  #trace debug info error warn
md5_key = "0000000000000000000000000000000"
[server]
host = "127.0.0.1"
port = 8093