[database]
url = "mongodb://localhost:27017"
db_name = "group"
[redis]
url = "redis://127.0.0.1:6379/"
[shard]
client_addr = "127.0.0.1:50000"
server_addr = "127.0.0.1:60000"
[server]
host = "127.0.0.1"
port = 8091
[sys]
log_leve = "warn"  #trace debug info error warn