// This file is @generated by prost-build.
/// *
/// 创建群组请求
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroupMsg {
    /// 新群组 ID
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
}
/// *
/// 解散群组请求
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DestroyGroupMsg {
    /// 被解散的群组 ID
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
}
/// *
/// 修改群组信息
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangeGroupMsg {
    /// 群组 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 群头像 URL
    #[prost(string, tag = "3")]
    pub avatar: ::prost::alloc::string::String,
    /// 群简介
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    /// 群公告
    #[prost(string, tag = "5")]
    pub notice: ::prost::alloc::string::String,
    /// 群标签（英文逗号分隔）
    #[prost(string, tag = "6")]
    pub tags: ::prost::alloc::string::String,
    /// 加群权限枚举
    #[prost(enumeration = "super::common::JoinPermission", tag = "7")]
    pub join_permission: i32,
    /// 是否允许被搜索
    #[prost(bool, tag = "8")]
    pub allow_search: bool,
    #[prost(string, tag = "9")]
    pub options: ::prost::alloc::string::String,
}
/// *
/// 申请加入群组
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestJoinGroupMsg {
    /// 目标群组 ID
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    /// 发起加入请求的用户 ID 列表（通常为单个）
    #[prost(string, repeated, tag = "2")]
    pub member_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// *
/// 处理加入请求（管理员操作）
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HandleJoinRequestMsg {
    /// 请求 ID（唯一标识）
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 被处理成员 ID
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
    /// true = 接受，false = 拒绝
    #[prost(bool, tag = "4")]
    pub accept: bool,
    /// 拒绝原因或备注
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    /// 操作者 ID（通常为管理员）
    #[prost(string, tag = "6")]
    pub operator_id: ::prost::alloc::string::String,
}
/// *
/// 邀请成员加入群组
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InviteMembersMsg {
    /// 邀请操作 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 被邀请成员列表
    #[prost(string, repeated, tag = "3")]
    pub member_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 邀请理由
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    /// 发起邀请人 ID
    #[prost(string, tag = "5")]
    pub inviter_id: ::prost::alloc::string::String,
}
/// *
/// 被邀请成员处理邀请请求
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HandleInviteMsg {
    /// 邀请 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 被邀请人 ID
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
    /// 是否接受邀请
    #[prost(bool, tag = "4")]
    pub accept: bool,
    /// 拒绝理由（如拒绝）
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
}
/// *
/// 移除成员请求
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveMembersMsg {
    /// 操作 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 被移除成员列表
    #[prost(string, repeated, tag = "3")]
    pub member_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 踢人原因
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    /// 操作者 ID（通常为管理员）
    #[prost(string, tag = "5")]
    pub operator_id: ::prost::alloc::string::String,
}
/// *
/// 成员主动退出群组
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExitGroupMsg {
    /// 操作 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 退出成员 ID
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
    /// 退出原因（可选）
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
/// *
/// 修改成员角色
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangeMemberRoleMsg {
    /// 操作 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 成员 ID
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
    /// 新角色（如 ADMIN, MEMBER）
    #[prost(enumeration = "super::common::GroupRoleType", tag = "4")]
    pub role: i32,
    /// 执行操作的用户 ID
    #[prost(string, tag = "5")]
    pub operator_id: ::prost::alloc::string::String,
    /// 变更原因
    #[prost(string, tag = "6")]
    pub reason: ::prost::alloc::string::String,
}
/// *
/// 成员禁言设置
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MuteMemberMsg {
    /// 操作 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 被禁言的成员 ID（支持多个时可改 repeated）
    #[prost(string, tag = "3")]
    pub member_ids: ::prost::alloc::string::String,
    /// true = 禁言, false = 取消禁言
    #[prost(bool, tag = "4")]
    pub mute: bool,
    /// 操作理由
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    /// 操作者 ID
    #[prost(string, tag = "6")]
    pub operator_id: ::prost::alloc::string::String,
}
/// *
/// 修改成员资料（如群昵称/头像等）
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateMemberProfileMsg {
    /// 操作 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 成员 ID
    #[prost(string, tag = "3")]
    pub member_id: ::prost::alloc::string::String,
    /// 群内昵称
    #[prost(string, tag = "4")]
    pub alias: ::prost::alloc::string::String,
    /// 群内头像 URL
    #[prost(string, tag = "5")]
    pub avatar: ::prost::alloc::string::String,
}
/// *
/// 转让群主操作
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferOwnershipMsg {
    /// 操作 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组 ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 接收者 ID
    #[prost(string, tag = "3")]
    pub new_owner_id: ::prost::alloc::string::String,
    /// 转让说明
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    /// 当前群主 ID
    #[prost(string, tag = "5")]
    pub operator_id: ::prost::alloc::string::String,
}
/// 群组节点消息类型枚举
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GroupNodeMsgType {
    /// 未知消息类型
    UnknownMsgType = 0,
    /// 创建群组（含初始信息和成员）
    CreateGroupMsgType = 1,
    /// 更新群组信息（名称、头像、描述等）
    ChangeGroupMsgType = 2,
    /// 解散群组（不可恢复）
    DestroyGroupMsgType = 3,
    /// 成员上线（连接建立或进入群）
    MemberOnlineMsgType = 4,
    /// 成员下线（断开连接或离开群）
    MemberOfflineMsgType = 5,
    /// 用户申请加入群组
    RequestJoinGroupMsgType = 6,
    /// 管理员处理入群申请（通过/拒绝）
    HandleJoinRequestMsgType = 7,
    /// 邀请成员入群
    InviteMembersMsgType = 8,
    /// 移除成员（管理员操作）
    RemoveMembersMsgType = 9,
    /// 成员主动退出群组
    ExitGroupMsgType = 10,
    /// 修改成员角色（如设为管理员）
    ChangeMemberRoleMsgType = 11,
    /// 设置或取消成员禁言
    MuteMemberMsgType = 12,
    /// 修改成员属性（昵称、备注等）
    UpdateMemberProfileMsgType = 13,
    /// 转让群主身份
    TransferOwnershipMsgType = 14,
    /// 受理邀请（被邀请人接受/拒绝）
    HandleInviteMsgType = 15,
}
impl GroupNodeMsgType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownMsgType => "UNKNOWN_MSG_TYPE",
            Self::CreateGroupMsgType => "CREATE_GROUP_MSG_TYPE",
            Self::ChangeGroupMsgType => "CHANGE_GROUP_MSG_TYPE",
            Self::DestroyGroupMsgType => "DESTROY_GROUP_MSG_TYPE",
            Self::MemberOnlineMsgType => "MEMBER_ONLINE_MSG_TYPE",
            Self::MemberOfflineMsgType => "MEMBER_OFFLINE_MSG_TYPE",
            Self::RequestJoinGroupMsgType => "REQUEST_JOIN_GROUP_MSG_TYPE",
            Self::HandleJoinRequestMsgType => "HANDLE_JOIN_REQUEST_MSG_TYPE",
            Self::InviteMembersMsgType => "INVITE_MEMBERS_MSG_TYPE",
            Self::RemoveMembersMsgType => "REMOVE_MEMBERS_MSG_TYPE",
            Self::ExitGroupMsgType => "EXIT_GROUP_MSG_TYPE",
            Self::ChangeMemberRoleMsgType => "CHANGE_MEMBER_ROLE_MSG_TYPE",
            Self::MuteMemberMsgType => "MUTE_MEMBER_MSG_TYPE",
            Self::UpdateMemberProfileMsgType => "UPDATE_MEMBER_PROFILE_MSG_TYPE",
            Self::TransferOwnershipMsgType => "TRANSFER_OWNERSHIP_MSG_TYPE",
            Self::HandleInviteMsgType => "HANDLE_INVITE_MSG_TYPE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_MSG_TYPE" => Some(Self::UnknownMsgType),
            "CREATE_GROUP_MSG_TYPE" => Some(Self::CreateGroupMsgType),
            "CHANGE_GROUP_MSG_TYPE" => Some(Self::ChangeGroupMsgType),
            "DESTROY_GROUP_MSG_TYPE" => Some(Self::DestroyGroupMsgType),
            "MEMBER_ONLINE_MSG_TYPE" => Some(Self::MemberOnlineMsgType),
            "MEMBER_OFFLINE_MSG_TYPE" => Some(Self::MemberOfflineMsgType),
            "REQUEST_JOIN_GROUP_MSG_TYPE" => Some(Self::RequestJoinGroupMsgType),
            "HANDLE_JOIN_REQUEST_MSG_TYPE" => Some(Self::HandleJoinRequestMsgType),
            "INVITE_MEMBERS_MSG_TYPE" => Some(Self::InviteMembersMsgType),
            "REMOVE_MEMBERS_MSG_TYPE" => Some(Self::RemoveMembersMsgType),
            "EXIT_GROUP_MSG_TYPE" => Some(Self::ExitGroupMsgType),
            "CHANGE_MEMBER_ROLE_MSG_TYPE" => Some(Self::ChangeMemberRoleMsgType),
            "MUTE_MEMBER_MSG_TYPE" => Some(Self::MuteMemberMsgType),
            "UPDATE_MEMBER_PROFILE_MSG_TYPE" => Some(Self::UpdateMemberProfileMsgType),
            "TRANSFER_OWNERSHIP_MSG_TYPE" => Some(Self::TransferOwnershipMsgType),
            "HANDLE_INVITE_MSG_TYPE" => Some(Self::HandleInviteMsgType),
            _ => None,
        }
    }
}
