// This file is @generated by prost-build.
/// *
/// 通用响应结构
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonResp {
    /// 是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 错误或提示信息
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// *
/// 群标签信息
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TagInfo {
    /// 标签唯一ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 标签名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 标签说明
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// 可选颜色代码（如 "#FF0000"）
    #[prost(string, tag = "4")]
    pub color: ::prost::alloc::string::String,
}
/// *
/// 群组基本信息（用于展示和配置）
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupEntity {
    /// 群组唯一ID（由系统生成）
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 群组名称（用户可见）
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 群头像URL
    #[prost(string, tag = "3")]
    pub avatar: ::prost::alloc::string::String,
    /// 群简介（支持富文本）
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    /// 群公告（群成员可见）
    #[prost(string, tag = "5")]
    pub notice: ::prost::alloc::string::String,
    /// 加群权限控制
    #[prost(enumeration = "JoinPermission", tag = "6")]
    pub join_permission: i32,
    /// 群标签（英文逗号分隔）
    #[prost(string, tag = "7")]
    pub owner_id: ::prost::alloc::string::String,
    /// 群组类型：0 普通群 / 1 超级群 / 2 系统群
    #[prost(int32, tag = "8")]
    pub group_type: i32,
    /// 是否允许通过搜索找到
    #[prost(bool, tag = "9")]
    pub allow_search: bool,
    /// 是否启用
    #[prost(bool, tag = "10")]
    pub enable: bool,
    /// 创建时间
    #[prost(uint64, tag = "11")]
    pub create_time: u64,
    /// 更新时间
    #[prost(uint64, tag = "12")]
    pub update_time: u64,
}
/// *
/// 群组成员详细信息
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMemberEntity {
    /// 成员记录ID（内部持久化用）
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 所属群组ID
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// 用户唯一ID
    #[prost(string, tag = "3")]
    pub uid: ::prost::alloc::string::String,
    /// 群内别名 / 昵称
    #[prost(string, tag = "4")]
    pub alias: ::prost::alloc::string::String,
    /// 成员角色
    #[prost(enumeration = "GroupRoleType", tag = "5")]
    pub role: i32,
    /// 是否禁言中（true=被禁言）
    #[prost(bool, tag = "6")]
    pub is_muted: bool,
    /// 成员头像URL（前端展示用）
    #[prost(string, tag = "7")]
    pub avatar: ::prost::alloc::string::String,
    /// 加入时间
    #[prost(uint64, tag = "8")]
    pub create_time: u64,
    /// 更新时间
    #[prost(uint64, tag = "9")]
    pub update_time: u64,
}
/// ==========================
/// 👤 客户端用户实体定义
/// ==========================
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientEntity {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 姓名
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    /// 密码
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
    /// 客户端用户 ID
    #[prost(string, tag = "5")]
    pub uid: ::prost::alloc::string::String,
    /// 是否启用（封号）
    #[prost(bool, tag = "6")]
    pub enable: bool,
    /// 是否锁定（禁止登录）
    #[prost(bool, tag = "7")]
    pub lock: bool,
    /// 头像 URL（可选，空字符串表示无）
    #[prost(string, tag = "8")]
    pub avatar: ::prost::alloc::string::String,
    /// 加好友策略
    #[prost(enumeration = "FriendPolicy", tag = "9")]
    pub allow_add_friend: i32,
    /// 用户基本信息字段（KV）
    #[prost(map = "string, string", tag = "10")]
    pub profile_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 扩展字段（KV，可为空）
    #[prost(map = "string, string", tag = "11")]
    pub extend_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 创建时间（Unix 秒）
    #[prost(uint64, tag = "99")]
    pub create_time: u64,
    /// 最后更新时间（Unix 秒）
    #[prost(uint64, tag = "100")]
    pub update_time: u64,
}
/// *
/// 群成员角色类型
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GroupRoleType {
    /// 群主（拥有最高权限）
    Owner = 0,
    /// 管理员（具备部分管理权限）
    Admin = 1,
    /// 普通成员
    Member = 2,
}
impl GroupRoleType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Owner => "OWNER",
            Self::Admin => "ADMIN",
            Self::Member => "MEMBER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OWNER" => Some(Self::Owner),
            "ADMIN" => Some(Self::Admin),
            "MEMBER" => Some(Self::Member),
            _ => None,
        }
    }
}
/// *
/// 加群权限控制类型
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JoinPermission {
    /// 任何人都可加入
    Anyone = 0,
    /// 加群需审批
    NeedApproval = 1,
    /// 仅允许通过邀请加入
    InviteOnly = 2,
    /// 不允许加入
    Closed = 3,
}
impl JoinPermission {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Anyone => "ANYONE",
            Self::NeedApproval => "NEED_APPROVAL",
            Self::InviteOnly => "INVITE_ONLY",
            Self::Closed => "CLOSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ANYONE" => Some(Self::Anyone),
            "NEED_APPROVAL" => Some(Self::NeedApproval),
            "INVITE_ONLY" => Some(Self::InviteOnly),
            "CLOSED" => Some(Self::Closed),
            _ => None,
        }
    }
}
/// *
/// 加群验证类型
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JoinQuestionType {
    /// 无验证
    None = 0,
    /// 答题验证
    Question = 1,
    /// 验证码验证
    Captcha = 2,
    /// 邀请码验证
    InviteCode = 3,
}
impl JoinQuestionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "NONE",
            Self::Question => "QUESTION",
            Self::Captcha => "CAPTCHA",
            Self::InviteCode => "INVITE_CODE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "QUESTION" => Some(Self::Question),
            "CAPTCHA" => Some(Self::Captcha),
            "INVITE_CODE" => Some(Self::InviteCode),
            _ => None,
        }
    }
}
/// ======================================
/// 💬 消息类型枚举（用于标记主消息类型）
/// ======================================
/// 每条消息将根据其主内容赋予一个主类型，便于前端渲染和后端分类处理。
/// 注意：具体内容仍以 MessageContent 的 oneof 实体为准，ContentType 仅为索引分类用途。
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ContentType {
    /// 未知类型：默认值，用于防御性处理或解析失败情况
    Unknown = 0,
    /// 文本消息：纯文本内容
    Text = 1,
    /// 图片消息：包含图片地址、尺寸、缩略图等信息
    Image = 2,
    /// 音频消息：语音聊天或语音留言
    Audio = 3,
    /// 视频消息：播放地址、封面图、时长等
    Video = 4,
    /// HTML 富文本消息：用于结构化卡片、网页链接等
    Html = 5,
    /// 位置消息：经纬度、地址描述等
    Location = 6,
    /// 文件消息：支持任意文件格式，如 PDF、Word、ZIP 等
    File = 7,
    /// 表情消息：标准 emoji 或自定义动态/静态表情
    Emoji = 8,
    /// 引用消息：引用历史消息的内容并附加回复
    Quote = 9,
    /// 音视频通话信令：如邀请、接听、挂断等
    AvCall = 10,
    /// VOIP 通话记录：用于保存通话日志
    Voip = 11,
    /// 通知消息：系统推送提示、公告等
    Notification = 12,
    /// 系统消息：如封号、强制下线、服务器维护通知等
    System = 13,
    /// 提醒消息：如代办事项、日程提醒等
    Reminder = 14,
    /// 好友事件：加好友、被删除、拉黑等事件
    FriendEvent = 15,
    /// 群组事件：如被踢出群、群解散、管理员变更等
    GroupEvent = 16,
    /// 消息撤回：通知客户端某条消息已被撤回
    Revoke = 17,
    /// 转发消息：引用其他消息的复用/转发版本
    Forward = 18,
    /// 可选扩展类型（根据业务需要添加）
    ///
    /// 名片消息：用户或群的联系人分享
    ContactCard = 19,
    /// 投票消息：包含投票标题、选项、结果等信息
    Vote = 20,
    /// 红包消息：用于节日、福利等场景
    RedEnvelope = 21,
    /// 自定义消息：开发者自定义结构，通常以 JSON 承载
    Custom = 100,
}
impl ContentType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Text => "TEXT",
            Self::Image => "IMAGE",
            Self::Audio => "AUDIO",
            Self::Video => "VIDEO",
            Self::Html => "HTML",
            Self::Location => "LOCATION",
            Self::File => "FILE",
            Self::Emoji => "EMOJI",
            Self::Quote => "QUOTE",
            Self::AvCall => "AV_CALL",
            Self::Voip => "VOIP",
            Self::Notification => "NOTIFICATION",
            Self::System => "SYSTEM",
            Self::Reminder => "REMINDER",
            Self::FriendEvent => "FRIEND_EVENT",
            Self::GroupEvent => "GROUP_EVENT",
            Self::Revoke => "REVOKE",
            Self::Forward => "FORWARD",
            Self::ContactCard => "CONTACT_CARD",
            Self::Vote => "VOTE",
            Self::RedEnvelope => "RED_ENVELOPE",
            Self::Custom => "CUSTOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "TEXT" => Some(Self::Text),
            "IMAGE" => Some(Self::Image),
            "AUDIO" => Some(Self::Audio),
            "VIDEO" => Some(Self::Video),
            "HTML" => Some(Self::Html),
            "LOCATION" => Some(Self::Location),
            "FILE" => Some(Self::File),
            "EMOJI" => Some(Self::Emoji),
            "QUOTE" => Some(Self::Quote),
            "AV_CALL" => Some(Self::AvCall),
            "VOIP" => Some(Self::Voip),
            "NOTIFICATION" => Some(Self::Notification),
            "SYSTEM" => Some(Self::System),
            "REMINDER" => Some(Self::Reminder),
            "FRIEND_EVENT" => Some(Self::FriendEvent),
            "GROUP_EVENT" => Some(Self::GroupEvent),
            "REVOKE" => Some(Self::Revoke),
            "FORWARD" => Some(Self::Forward),
            "CONTACT_CARD" => Some(Self::ContactCard),
            "VOTE" => Some(Self::Vote),
            "RED_ENVELOPE" => Some(Self::RedEnvelope),
            "CUSTOM" => Some(Self::Custom),
            _ => None,
        }
    }
}
/// ======================================
/// 🎯 聊天目标类型枚举
/// ======================================
/// 用于标识消息的接收目标类型，帮助客户端和服务端进行不同的处理逻辑
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChatTargetType {
    /// 未知类型：默认值，用于防御性处理或解析失败情况
    UnKnown = 0,
    /// 群聊目标：消息发送到群组
    Group = 1,
    /// 单聊目标：消息发送到个人用户
    Single = 2,
}
impl ChatTargetType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnKnown => "UN_KNOWN",
            Self::Group => "GROUP",
            Self::Single => "SINGLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UN_KNOWN" => Some(Self::UnKnown),
            "GROUP" => Some(Self::Group),
            "SINGLE" => Some(Self::Single),
            _ => None,
        }
    }
}
/// ======================================
/// 📦 字节消息类型枚举
/// ======================================
/// 用于标识通过 WebSocket 传输的二进制消息类型
/// 这些类型用于消息路由和分发，确保消息被正确处理
/// 消息类型枚举：用于标识通信协议中的消息分类
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ByteMessageType {
    /// 未知消息类型（默认）：用于解析错误或未定义处理
    UnknownByteMessageType = 0,
    /// 系统基础通信（1~9）
    ///
    /// 心跳消息：保持连接活跃
    HeartbeatMsgType = 1,
    /// 认证请求：客户端发起身份验证
    LoginReqMsgType = 2,
    /// 认证响应：服务端返回认证结果
    LoginRespMsgType = 3,
    /// 登出请求：客户端主动断开连接
    LogoutReqMsgType = 4,
    /// 登出响应：服务端确认登出状态
    LogoutRespMsgType = 5,
    /// 验证码请求：短信/邮件验证码发送请求
    SendVerificationCodeReqMsgType = 6,
    /// 验证码响应：验证码发送处理结果
    SendVerificationCodeRepMsgType = 7,
    /// 系统通知：平台或服务级消息
    SystemNotificationMsgType = 8,
    /// 用户刷新：资料/状态/配置变更通知
    UserFlushMsgType = 9,
    /// 用户在线状态（10~19）
    ///
    /// 用户上线通知
    OnlineStatusMsgType = 10,
    /// 用户下线通知
    OfflineStatusMsgType = 11,
    /// 聊天消息（20~29）
    ///
    /// 单聊消息
    UserMsgType = 20,
    /// 群聊消息
    GroupMsgType = 21,
    /// 好友 / 群组事件（30~39）
    ///
    /// 好友事件：申请、同意、删除等
    FriendEventMsgType = 30,
    /// 群创建通知
    GroupCreateMsgType = 31,
    /// 群解散通知
    GroupDismissMsgType = 32,
}
impl ByteMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownByteMessageType => "UNKNOWN_BYTE_MESSAGE_TYPE",
            Self::HeartbeatMsgType => "HeartbeatMsgType",
            Self::LoginReqMsgType => "LoginReqMsgType",
            Self::LoginRespMsgType => "LoginRespMsgType",
            Self::LogoutReqMsgType => "LogoutReqMsgType",
            Self::LogoutRespMsgType => "LogoutRespMsgType",
            Self::SendVerificationCodeReqMsgType => "SendVerificationCodeReqMsgType",
            Self::SendVerificationCodeRepMsgType => "SendVerificationCodeRepMsgType",
            Self::SystemNotificationMsgType => "SystemNotificationMsgType",
            Self::UserFlushMsgType => "UserFlushMsgType",
            Self::OnlineStatusMsgType => "OnlineStatusMsgType",
            Self::OfflineStatusMsgType => "OfflineStatusMsgType",
            Self::UserMsgType => "UserMsgType",
            Self::GroupMsgType => "GroupMsgType",
            Self::FriendEventMsgType => "FriendEventMsgType",
            Self::GroupCreateMsgType => "GroupCreateMsgType",
            Self::GroupDismissMsgType => "GroupDismissMsgType",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_BYTE_MESSAGE_TYPE" => Some(Self::UnknownByteMessageType),
            "HeartbeatMsgType" => Some(Self::HeartbeatMsgType),
            "LoginReqMsgType" => Some(Self::LoginReqMsgType),
            "LoginRespMsgType" => Some(Self::LoginRespMsgType),
            "LogoutReqMsgType" => Some(Self::LogoutReqMsgType),
            "LogoutRespMsgType" => Some(Self::LogoutRespMsgType),
            "SendVerificationCodeReqMsgType" => {
                Some(Self::SendVerificationCodeReqMsgType)
            }
            "SendVerificationCodeRepMsgType" => {
                Some(Self::SendVerificationCodeRepMsgType)
            }
            "SystemNotificationMsgType" => Some(Self::SystemNotificationMsgType),
            "UserFlushMsgType" => Some(Self::UserFlushMsgType),
            "OnlineStatusMsgType" => Some(Self::OnlineStatusMsgType),
            "OfflineStatusMsgType" => Some(Self::OfflineStatusMsgType),
            "UserMsgType" => Some(Self::UserMsgType),
            "GroupMsgType" => Some(Self::GroupMsgType),
            "FriendEventMsgType" => Some(Self::FriendEventMsgType),
            "GroupCreateMsgType" => Some(Self::GroupCreateMsgType),
            "GroupDismissMsgType" => Some(Self::GroupDismissMsgType),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Gender {
    /// 未知
    Unknown = 0,
    /// 男性
    Male = 1,
    /// 女性
    Female = 2,
}
impl Gender {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::Male => "Male",
            Self::Female => "Female",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unknown" => Some(Self::Unknown),
            "Male" => Some(Self::Male),
            "Female" => Some(Self::Female),
            _ => None,
        }
    }
}
/// ==========================
/// 🚦 加好友策略（枚举定义）
/// ==========================
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FriendPolicy {
    /// 允许任何人添加好友
    AllowAny = 0,
    /// 需要验证
    NeedConfirm = 1,
    /// 拒绝任何人添加
    DenyAny = 2,
}
impl FriendPolicy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AllowAny => "ALLOW_ANY",
            Self::NeedConfirm => "NEED_CONFIRM",
            Self::DenyAny => "DENY_ANY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALLOW_ANY" => Some(Self::AllowAny),
            "NEED_CONFIRM" => Some(Self::NeedConfirm),
            "DENY_ANY" => Some(Self::DenyAny),
            _ => None,
        }
    }
}
