// This file is @generated by prost-build.
/// 基础请求，仅包含节点地址
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BaseRequest {
    /// 节点地址（如 192.168.1.10:9000）
    #[prost(string, tag = "1")]
    pub node_addr: ::prost::alloc::string::String,
}
/// 通用响应结构（统一 success + message）
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonResp {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// ============================
/// 分片节点元信息
/// ============================
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShardNodeInfo {
    /// 所属节点地址
    #[prost(string, tag = "1")]
    pub node_addr: ::prost::alloc::string::String,
    /// 当前版本号（用于 CAS 检查）
    #[prost(uint64, tag = "2")]
    pub version: u64,
    /// 当前状态
    #[prost(enumeration = "ShardState", tag = "3")]
    pub state: i32,
    /// 最后更新时间戳（毫秒）
    #[prost(uint64, tag = "4")]
    pub last_update_time: u64,
}
/// ============================
/// 请求结构：更新分片状态
/// ============================
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateShardStateRequest {
    #[prost(string, tag = "1")]
    pub node_addr: ::prost::alloc::string::String,
    #[prost(enumeration = "ShardState", tag = "2")]
    pub new_state: i32,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListShardNodesResponse {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<ShardNodeInfo>,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAllNodesResponse {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<ShardNodeInfo>,
}
/// =====================
/// 枚举：分片节点状态定义
/// =====================
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ShardState {
    /// 未指定状态（默认值）
    Unspecified = 0,
    /// 分片正常运行中
    Normal = 1,
    /// 正在迁移（目标节点未确认接管）
    Migrating = 2,
    /// 异常（节点宕机或下线，待仲裁）
    Failed = 3,
    /// 接管准备阶段
    Preparing = 4,
    /// 可切换 owner
    Ready = 5,
    /// 节点主动下线，该分片不再调度
    Offline = 6,
    /// 节点准备下线，等待数据迁移或状态确认
    PreparingOffline = 7,
}
impl ShardState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "UNSPECIFIED",
            Self::Normal => "NORMAL",
            Self::Migrating => "MIGRATING",
            Self::Failed => "FAILED",
            Self::Preparing => "PREPARING",
            Self::Ready => "READY",
            Self::Offline => "OFFLINE",
            Self::PreparingOffline => "PREPARING_OFFLINE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED" => Some(Self::Unspecified),
            "NORMAL" => Some(Self::Normal),
            "MIGRATING" => Some(Self::Migrating),
            "FAILED" => Some(Self::Failed),
            "PREPARING" => Some(Self::Preparing),
            "READY" => Some(Self::Ready),
            "OFFLINE" => Some(Self::Offline),
            "PREPARING_OFFLINE" => Some(Self::PreparingOffline),
            _ => None,
        }
    }
}
