use biz_core::protocol::msg::message::Segment;

// This file is @generated by prost-build.
/// ======================================
/// 👤 用户消息结构（单聊消息）
/// ======================================
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserMsgEntity {
    /// 当前消息唯一 ID
    #[prost(uint64, tag = "1")]
    pub message_id: u64,
    /// 发送者用户ID
    #[prost(string, tag = "2")]
    pub from: ::prost::alloc::string::String,
    /// 接收者用户ID
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    /// 消息内容
    #[prost(message, repeated, tag = "4")]
    pub content: ::prost::alloc::vec::Vec<Segment>,
    /// 阅读时间
    #[prost(int64, tag = "5")]
    pub read_time: i64,
    /// 是否撤回
    #[prost(bool, tag = "6")]
    pub revoked: bool,
    /// 是否系统消息
    #[prost(bool, tag = "7")]
    pub is_system: bool,
    /// 是否同步到 MQ
    #[prost(bool, tag = "8")]
    pub sync_mq_status: bool,
    /// 是否送达
    #[prost(bool, tag = "9")]
    pub delivered: bool,
    /// 创建时间
    #[prost(int64, tag = "99")]
    pub created_time: i64,
    /// 最后更新时间
    #[prost(int64, tag = "100")]
    pub updated_time: i64,
}
