// This file is @generated by prost-build.
/// 用户消息结构
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserMessage {
    /// 全局唯一消息 ID（如雪花 ID）
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 所属商户
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    /// 所属用户 ID
    #[prost(string, tag = "3")]
    pub from: ::prost::alloc::string::String,
    /// 目标 ID
    #[prost(string, tag = "4")]
    pub to: ::prost::alloc::string::String,
    /// 消息复合内容（支持结构化消息段）
    #[prost(message, repeated, tag = "5")]
    pub content: ::prost::alloc::vec::Vec<super::message::Segment>,
    /// 创建时间（Unix 秒时间戳）
    #[prost(int64, tag = "6")]
    pub created_time: i64,
    /// 最后更新时间（Unix 秒时间戳）
    #[prost(int64, tag = "7")]
    pub updated_time: i64,
    /// 是否被撤回
    #[prost(bool, tag = "8")]
    pub revoked: bool,
    /// 是否为系统消息
    #[prost(bool, tag = "9")]
    pub is_system: bool,
    /// 是否已发送到 MQ
    #[prost(bool, tag = "10")]
    pub sync_mq_status: bool,
    /// 是否已送达客户端
    #[prost(bool, tag = "11")]
    pub delivered: bool,
    /// 阅读时间戳（可选）
    #[prost(int64, tag = "12")]
    pub read_time: i64,
}
/// 群组消息结构
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMessage {
    /// 全局唯一消息 ID（如雪花 ID）
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 所属商户
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    /// 所属群组 ID
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    /// 发送者用户 ID
    #[prost(string, tag = "4")]
    pub from: ::prost::alloc::string::String,
    /// 消息复合内容（支持结构化消息段）
    #[prost(message, repeated, tag = "5")]
    pub content: ::prost::alloc::vec::Vec<super::message::Segment>,
    /// 创建时间（Unix 秒时间戳）
    #[prost(int64, tag = "6")]
    pub create_time: i64,
    /// 最后更新时间（Unix 秒时间戳）
    #[prost(int64, tag = "7")]
    pub update_time: i64,
    /// 群内顺序号（用于顺序拉取）
    #[prost(int64, tag = "8")]
    pub seq: i64,
    /// 是否已发送到 MQ
    #[prost(bool, tag = "9")]
    pub sync_mq_status: bool,
    /// 是否被撤回
    #[prost(bool, tag = "10")]
    pub revoked: bool,
    /// 是否为系统消息（可用于区分人工发送和自动提示）
    #[prost(bool, tag = "11")]
    pub is_system: bool,
}
